### ISSUE TITLE
Support default phoenix apps with additional options for ModuleFilename

### ISSUE THREAD

**Issue by sitch** [mirego/credo_naming#11] opened 2020-05-06 19:09 UTC
Currently if you have something like 
```elixir
defmodule MyAppWeb.MyController` do
``` 
phoenix will put this into 
```shell
/my_app_web/controllers/my_controller.ex
```

So it would be useful if either in acronyms or substitutions where you could say 
```elixir
[{"my_app_web/controllers/, "my_app_web/"}]
```

**Comment by remi** [comment] 2020-05-07 09:47
Hi @sitch,

This is a duplicate of #3 where I posted a kind of workaround.

In the current README.md there is this note:

> In the future, there may be some “naming convention flavours” (eg. :default, :phoenix, etc.) to use instead of having to implement your own callback.

So if you implement a `valid_filename_callback` to match the naming pattern used in Phoenix, please share 😄 

Cheers!

**Closed by remi** 2020-05-07 09:47 UTC

**Comment by sitch** [comment] 2020-05-08 02:25
Oh kickass thanks!

**Comment by sitch** [comment] 2020-05-08 02:28
For anyone else with a similiar phoniex-esque layout (just find and replace `my_app` with your app name): 
```elixir
        {
          CredoNaming.Check.Consistency.ModuleFilename,
          excluded_paths: ["config", "mix.exs"],
          valid_filename_callback: fn
            "lib/my_app_web/channels/" <> filepart, module_name, opts ->
              valid_filename?("lib/my_app_web/" <> filepart, module_name, opts)

            "lib/my_app_web/controllers/" <> filepart, module_name, opts ->
              valid_filename?("lib/my_app_web/" <> filepart, module_name, opts)

            "lib/my_app_web/views/" <> filepart, module_name, opts ->
              valid_filename?("lib/my_app_web/" <> filepart, module_name, opts)

            "test/my_app_web/channels/" <> filepart, module_name, opts ->
              valid_filename?("test/my_app_web/" <> filepart, module_name, opts)

            "test/my_app_web/controllers/" <> filepart, module_name, opts ->
              valid_filename?("test/my_app_web/" <> filepart, module_name, opts)

            "test/my_app_web/views/" <> filepart, module_name, opts ->
              valid_filename?("test/my_app_web/" <> filepart, module_name, opts)

            filename, module_name, opts ->
              valid_filename?(filename, module_name, opts)
          end
        },
```
